# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:title.html
relative_permalinks: true

# Setup
title:               简媜
tagline:             '四月裂帛'
description:         '发发文章写写字'
url:                 http://yclub.github.io/jianzheng/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              简媜
  url:               http://yclub.github.io/jianzheng/
  email:             

# Custom vars
version:             1.0.0
