# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink 前不加斜杠，url后不加斜杠
permalink:           :categories/:title.html
relative_permalinks: true

# Setup
title:               简媜
tagline:             ''
description:         '三月的天书都印错，竟无人知晓'
url:                 http://jianzheng.yidie.org
baseurl:             'http://jianzheng.yidie.org'
paginate:            5

# About/contact
author:
  name:              简媜
  url:               http://jianzheng.yidie.org
  email:             

# Custom vars
version:             3
